fixtures:
  repositories:
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: https://github.com/hercules-team/augeasproviders_shellvar.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
    rsyslog:
      repo: https://github.com/saz/puppet-rsyslog.git
    network:
      repo: https://github.com/voxpupuli/puppet-network.git
      ref: v2.1.0
  symlinks:
    mofed: "#{source_dir}"
