---
.travis.yml:
  user: treydock
  secure: "MbQg0XLyQqVTtHXoW6gbwfYRicn41aSGF9WiZufahxgbuQKkesJejZyMm5Jb5DO94aYqsD/Wm5DswNr9VLsKZz4qW/bDAcyUhr6vUl95anGdFjFLh7uDylYe15v0lvfExSrMPoX5NfYVZGntjW9K0rXkkf+6/lN1SJvMX45zCKrAnKWkJZCmPcW5eMdVQnuIDVzKV4PqKHj2FCo8+APkJ2xkoVC3Nn2OFoJLQi+GuYiquYnNDCO121NSOz5Dn1ATaZ5wpgP2gTRGUEjlVBCrBvkOa54ZYxK04FiQCM72I2mXCQE4EXJkoXi5pkqR/F0yH+KQbny/7Ctq9ERr1+biogqiYY0yTbk9ySKlK+P51HTjxOjTUH545ywlIFw+EEYld2FOBfuMhAQSHl+gThEToJAABrOfKo5ag6SOOQeKdA0dWshOYtGRnivQvKM+C1FfVWmsEQhEh/7bw737kPFqpumasSrgLBRcTwcZVsIJ9/ulQuWLqdgcS2C92qjwJpqGVrzy+5u7kYSn2H9Jg/brwabZ/AiHN5I1qwWOUGXYl8MzOW/WlR5G6b3zESQ6ah2n6iPZNeywPictvky4J1/UZRZFdpCAy4jf2yS32xiI1jccEgfj1yM9A9MFsxVY0kGv005SrYWOVIVzbJiX25Q9+PfBUok2Emf9uinmff4o6hQ="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
