---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
notifications:
  email: false
