---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake release_checks
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.4
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
    - rvm: 2.5.1
      env: PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES="yes"
notifications:
  email: false
